norm-l/odx

- src/components/BaseComponents/TextInput/TextInput.tsx
- src/components/forms/Email/index.tsx
- src/components/forms/Phone/index.tsx
- src/components/forms/TextInput/index.tsx
Raising PR for review -
This change adds the GDS Styled Text Input base component, which is then used by the SDK Text Input component.
Phone and Email fields have also been updated to use the SDK Text input component, passing relevant input props.
The base component can optionally wrap it's label in a `<h1>` (to comply with GDS guidance about 'single question pages'), optionally display hint and/or error text (if they are provided) 
The base component also contains a 'ConditionalWrap' helper function, which may need to be refactored out for use in other components in future.
The SDK Text Input component contains some new logic to test if there is only one editable field in this view, which in turn directs the base component to display the label as a header or not, and also updates the …
> Text input component - Change Review

- tests/unit/components/BaseComponents/Select.test.tsx
- tests/unit/components/BaseComponents/TextInput.test.tsx
- tests/unit/components/BaseComponents/__snapshots__/Select.test.tsx.snap
- tests/unit/components/BaseComponents/__snapshots__/TextInput.test.tsx.snap
Adds some basic snapshot tests for sanity checking future changes to Text input and Select components
running npm run test-jest will generate 'rendered' components, and compare against the saved snapshots included with this PR.
If there are any differences, these will be highlighted in the test report. 
IF the changes are expected and required, pressing 'u' while in the test report cli interface will regenerate the snapshots, which should be included in the PR for the change.
Currently these tests will need to be run manually by developers as they are not run as part of any build steps.
> Adds initial snapshot tests for Text Input and Select components

- src/components/forms/RadioButtons/index.tsx
Correctly passes hintText and ErrorText values to radio button components
(Also adds the functionality to update the page title to display error when error happens, although this will likely be over ruled by another fix to come)
> BUG-5776 - Radio error fix

- src/components/Assignment/index.tsx
- src/components/FlowContainer/index.tsx
- src/components/forms/Dropdown/index.tsx
- src/components/forms/RadioButtons/index.tsx
- src/components/forms/TextInput/index.tsx
- src/helpers/hooks/QuestionDisplayHooks.ts
This change conditionally shows the step name as heading at assignment component if there is more than one field on the page. Otherwise it doesn't not display the heading, as this will be shown as part of the only field.
Functionality to set a field label to be the step name if it is the only field has been removed, as this will be handled pega side (Appropriate labels should be set in app)
> BUG-5790 (and related bugs) Resolves the duplicated heading issue

- src/components/templates/DefaultForm/index.tsx
Fixes check answers screen layout issue by passing 'hasBeenWrapped' prop, to stop nested <dl> components.
> BUG-5985 - Passes hasBeenWrapped prop properly to child components of Default Form

- src/components/BaseComponents/Checkboxes/Checkbox.tsx
- src/components/forms/Checkbox/index.tsx
Corrected checkboxes to show as checked if returned to after progressing through an assignment.
Also pass 'frontend' true and false values to read only component instead of backend 'true/false'
> US-9525 React Task - Checkboxes reflect selected value

- src/helpers/hooks/QuestionDisplayHooks.ts
Updates the 'single editable input' hook logic to check that if there is only one editable field, it is the first thing on the page. Otherwise it should be considered to use it's own label and not the assignment title should not be hidden.
> Bug 5925 - Fixes issue where in put on check answers screen takes the page title

- src/components/Assignment/index.tsx
- src/components/BaseComponents/DateInput/DateInput.tsx
- src/components/forms/Date/index.tsx
- src/helpers/formatters/DateErrorFormatter.js
- tests/unit/components/BaseComponents/__snapshots__/DateInput.test.tsx.snap
In the case of missing day, month and/or year - displays a message pointing out what is missing. Error highlights the fields that are missing, and sets the summary link to point to the first missing element. 
In case of invalid date, - updates the message to follow format '[property name] must be a real date'
> Manually reformats error messages for date component to be more GDS aligned

- src/applications/AppSelector/index.tsx
- src/helpers/config_access.js
This change allows for various paths such as /dt1/ and /stg1/ for the website hosted on fastshosts to now correctly route to the child benefit application
Due to there being paths in fasthosts, a further change is required to ensure that constellation is using files from the subfolder as opposed to the root folder (in case we need to version constellation between environments)
> Fast hosts ref changes (US-10173)

- src/components/BaseComponents/Button/Button.tsx
Small fix to the styling of 'link' buttons.
Classes were being overwritten by extra attributes. Now any classNames passed via attributes are appended to the default link style class.
> Link button classes now correctly handled

- src/applications/ChildBenefitsClaim/index.tsx
Adds fix to ensure that container is cleared clicking 'save and come back' button - as this without this the next open Assignment calls would fail.
Hook into this event with the Create_State_Saved event.
Also adds hidden text for the Submitted claims View claim' button to provide metadata for assistive tech users.
> Portal fixes sprint4

- src/applications/ChildBenefitsClaim/index.tsx
- src/components/Assignment/index.tsx
- src/components/ViewContainer/index.tsx
- src/helpers/setPageTitleHelpers.ts
To align with GDS specifications and accessibility guidelines, the Page title, should reflect where the user is in the process.
New helper created to set the page title in format: 
<\<page heading\>> - <\<service name\>> - GOV.UK 
This helper is then called from the application page, whenever the page display state toggles are changed
Also called in the assignment component whenever children update, to reflect the stage heading.
Also called in Viewcontainer component to update the title when on the Claim Summary page for submitted claims.
> BUG-6389 - Update page title when progressing through the application

- src/components/forms/Group/index.tsx
- added heading to group, to show label in the groups that are not checkbox groups (e.g. Are you claiming Child benefit page)
- passed the instructions for checkbox group to hintText
> bug-6107 fixed

- package.json
Pega Platform has been upgraded to 8.8.3 for environments DT1 and STG1 as of 12/07/23
PROD1 will be upgraded on 25/07/23 (accurate as of today)
> bumped to match platform upgraded version of 8.8.3

- src/components/AppComponents/LanguageToggle/index.tsx
- src/components/helpers/utils.ts
- src/components/override-sdk/field/Dropdown/Dropdown.tsx
- src/components/override-sdk/field/RadioButtons/RadioButtons.tsx
- src/components/override-sdk/infra/ActionButtons/ActionButtons.tsx
- src/components/override-sdk/infra/Assignment/Assignment.tsx
- src/components/override-sdk/infra/FlowContainer/FlowContainer.tsx
- src/components/override-sdk/infra/View/View.tsx
- src/components/override-sdk/template/CaseView/CaseView.tsx
- src/components/override-sdk/template/Details/Details.tsx
- src/samples/ChildBenefitsClaim/index.tsx
After upgrading to 8.23.11, the pega fixes for localisation were not being pulled through into our overridden components.
This change pulls the relevant code into the overidden components, and also implements some supporting changes to ensure that localisation 'data' is refreshed with language toggle.
> BUG-6674 - Localisation logic added to overridden components

- src/components/helpers/HMRCAppContext.tsx
- src/components/helpers/hooks/QuestionDisplayHooks.ts
- src/components/override-sdk/template/DefaultForm/DefaultForm.tsx
- src/components/override-sdk/template/FieldGroupTemplate/FieldGroupTemplate.tsx
Alignment issues on the CYA pages were being caused by nested <dl> elements being generated.
This fix adds a new context to use in read only Default form components, ensuring any nested default forms will not render a <dl> component if they have already been wrapped.
> BUG-6543 - Fix alignment issues on CYA page

- src/components/custom-sdk/template/MimicASentence/MimicASentence.tsx
- src/components/helpers/hooks/QuestionDisplayHooks.ts
- src/components/override-sdk/field/TextInput/TextInput.tsx
Text and mimic a sentence fields now register to the global state if they are 'disabled' - (as they are for check address and check name, to allow the only field display logic to correctly display the page heading.
> BUG-7031 - Add page display handling for pages with read only information display

- src/components/override-sdk/template/DefaultForm/DefaultForm.tsx
Updates Default Form instruction text logic to only 'pass-through' instruction text if it has not already been display in Default form
> BUG-7216 - Remove duplicated instruction text

- src/components/override-sdk/template/DefaultForm/DefaultForm.tsx
To resolve an issue where all summary fields for legacy cases hit an error due to no assignment info in case info, added handling for this situation
>  Bug 7009 - 2 - Default forms handle missing assignment info 

- src/components/override-sdk/infra/Assignment/Assignment.tsx
Used an identifier to make sure the title shows when the declaration is loaded.
> BUG-7023 Missing title on declaration page

- src/components/override-sdk/field/Checkbox/Checkbox.tsx
Errors for declaration checkboxes not appearing have used the HMRCAppContext to identify the view by name, then I'm wrapping the checkboxes in their own individual groups. This means we get the red border and the error message is assigned correctly.
> Bug 7290 Errors for declaration checkboxes not appearing

- sdk-local-component-map.js
- src/components/helpers/formatters/ParsedHtml.tsx
- src/components/helpers/hooks/QuestionDisplayHooks.ts
- src/components/override-sdk/field/RichText/RichText.tsx
- src/components/override-sdk/field/RichText/index.tsx
- src/components/override-sdk/infra/Assignment/Assignment.tsx
Adds a basic implementation of the Rich Text component to fulfil the requirements of US-9579, displaying of informational text with full markup
- Currently, the Rich Text components always displays the 'inputs' value run through a HTML parser as it is not expected that we will need a fully functional Rich Text editor within the application.
TO NOTE: The Parsed HTML component has added some config to configure DOMPurify to retain target attribute of '_blank' on <a> tags, and also adds noopener and noreferrer rel tags for basic security. This should mean that any a tags passed from pega config should now work correctly if configured to open in new tab.
> US-9579 RichText Component handling (for use to display process advice with links)

- src/components/override-sdk/field/TextInput/TextInput.tsx
- src/components/override-sdk/infra/Assignment/Assignment.tsx
name and id was undefined because address is coming as children from pega so we have added a OR condition when name is not available on parent then search on child.
> Bug- 7534: Fixed address error bug

- src/components/override-sdk/infra/Assignment/Assignment.tsx
Sorting logic is not working properly because displayOrder is not correct when form elements are not coming on same level from pega. By removing sorting logic, we are able to fixed issue on all screens except one which require pega change.
> BUG-6776: Fixed error sequence issue on all screen except one

- src/components/BaseComponents/DateInput/DateInput.tsx
- src/components/BaseComponents/Select/Select.tsx
- src/components/BaseComponents/TextInput/TextInput.tsx
Accessibility failure: [1.3.2 Meaningful Sequence](https://www.w3.org/WAI/WCAG22/Understanding/meaningful-sequence.html)
Text descriptions should match the visual order e.g., our component structure for a Text Input is..
Label
Hint
Error
Control
This error was raised as the error was being read _before_ the hint.  I switched this around in the necessary components to ensure the correct order
```
const describedByIDs = `${hintText ? makeHintId(name) : ''} ${
errorText ? makeErrorId(name) : ''
}`.trim();
```
For radio buttons, checkbox groups etc we use a fieldset component which was already using the correct order so no changes there.
Lots of linting changes outside of this.
> BUG-7384 - Re-ordered describeBy IDs to match visual order

- src/components/AppComponents/LanguageToggle/index.tsx
When users switches to Welsh in language toggle lang attribute on html element doesn't reflect the change, not changed to cy .
Some pages have incomplete Welsh language translations. Missing lang="cy" attribute on Welsh copy. As this is not marked up with the appropriate language attribute to differentiate it from the other content, screen readers will not pronounce this correctly."
Missing Welsh translations, including visually hidden copy ie 'Support links' in footer when language switched to Welsh
Resolve: Add the required Welsh translations. lang attribute should reflect current state of the page and content
> BUG-7381 fixed html dom language tag on toggle

- src/components/helpers/hooks/useServiceShuttered.ts
- src/components/override-sdk/infra/Assignment/Assignment.tsx
- src/samples/ChildBenefitsClaim/ConfirmationPage.tsx
- src/samples/ChildBenefitsClaim/StartPage.tsx
Problem -
Shuttering the Child beneft service is ON Claimant is still able to click
"Begin new claim", "start now" 
"Accept and send"
"Continue claim"
Solution - 
Prepared a common hook to show service unavailable page if Shuttering is ON
Changes- 
Assignment.tsx - Code optimisation - Call to shutter hook added & previous implementation has been removed 
ConfirmationPage.tsx - Implementation was missing on this page, added 1line call to hook and updated render part
StartPage.tsx- Implementation was missing on this page, added 1line call to hook and updated render part
> fix: BUG-7599 Shuttering service

- src/samples/ChildBenefitsClaim/index.tsx
Initially their was delay in displaying the service error when the GetIndividual & GetRelationship API are turned off
Fixed the delayed by modifying below function
resetAppDisplay() & displayServiceNotAvailable()
> BUG-7305 Resolved Delay in displaying Service Error

- assets/css/appStyles.scss
- src/components/BaseComponents/Select/Select.tsx
- src/components/helpers/utils.ts
- Reverted changes of Bug-7308
- Added conditional fix for Bug-7308
- FieldSet wraper is not required in select component when select component is not alone on screen
> Bug-7308: Removed fieldset conditionally from select component 

- src/components/custom-sdk/field/HMRC_ODX_ComplexQuestionExplanation/index.tsx
Adds handling for warning text display in ComplexQuestionExplanaiton and hides when readonly
Adds a variant of the handling for Warning Text display to the ComplexQuestionExplanation component, which does not rely on the <strong> tag
Also added fix to hide explanation text in the summary page.
> US-9579 - fix warning text display

- src/samples/ChildBenefitsClaim/index.tsx
As a part of this we are reverting pega_app flag as true which was modified as a part of bug 7310.
Now that we are able to call generics api on each page load or new page fetch , so that we can update content with correct language.
> A fix for bug 7310 to get correct welsh content

- src/samples/ChildBenefitsClaim/ConfirmationPage.tsx
This PR is raised to remove un wanted string from case id and so we are correctly displaying the ref id now.
> US-12118 : PR for small modification

- src/components/BaseComponents/ReadOnlyDisplay/ReadOnlyDisplay.tsx
- src/components/override-sdk/field/TextInput/TextInput.tsx
Common logic to separate out Comma(,) concatenated fields to make them appear on next line for 'CSV' field.
Refer screenshot below -
> feat: US10790 - Check your answers - Provision to appear comma separated value

- assets/i18n/cy.json
- assets/i18n/en.json
- src/components/helpers/utils.ts
- src/components/override-sdk/infra/ActionButtons/ActionButtons.tsx
- src/components/override-sdk/infra/AssignmentCard/AssignmentCard.tsx
As a part of this User story  , Save and come back link is been removed.
cancel button is renamed to close claim.
created a common functionality and placed it in utils , so if any un-auth related story comes in near future, we can use that functionality for conditioning.
> US-12284 : Remove save and come back link , rename cancel button in Un-Auth journey

- src/samples/ChildBenefitsClaim/ConfirmationPage.tsx
As per the comment given by Alex on US-12336 , we need to replace the text "takes 30 seconds" to "opens in new tab"
at the confirmation screen.
> US-12336 : Replace text takes 30 seconds to opens in new tab

- src/components/custom-sdk/template/HMRC_ODX_GDSSummaryCard/index.tsx
- src/components/helpers/utils.ts
- When there is only one item on the add more details screen for Country, Nationality, Name and Children, remove button should not be displayed to the user.
- Removed existing important banner message (upon clicking remove button on the last item)
Screenshots - 
**Nationality** - For Two cards 
**Nationality** - For only one card
**Names**
> feat:US12545 - Hiding remove link

- src/components/BaseComponents/ReadOnlyDisplay/ReadOnlyDisplay.tsx
- src/components/override-sdk/field/AutoComplete/AutoComplete.tsx
Bug-7965: added check if formattedValue is undefined then use value
Bug-7944: We are getting value as "IND" from pega so we are extracting value from option list by filtering and sending proper value to readonly component.
> Fixed Bug-7965 & Bug-7944

- assets/i18n/cy.json
- assets/i18n/en.json
- src/components/override-sdk/infra/ActionButtons/ActionButtons.tsx
Currently, the claimant has to click on 'Continue' button to save and go to the next page. To make it more complaint with GDS, the Continue button has to be amended as 'Save and continue' and 'Cancel' button will be removed for auth hourney.
Note: Continue button will only be amended with 'Save and continue' and the action for the button will not be changed. This is only for Auth journey.
> Us 12668 - Remove "Cancel" button and change "Continue" to be "Save and continue" on auth journey only

- src/components/BaseComponents/FormGroup/FormGroup.tsx
Some of the pages where Autocomplete component is used, React is not rendering the component in proper order when user come from portal page after clicking cancel or save and come back later. 
We have tried multiple solution like adding <></> but only adding `<div>` works.
> Bug-7984: Fixed rendering order issue

- src/components/override-sdk/infra/Assignment/Assignment.tsx
I've added some fields into each error message object that is created. I've then added function which runs the clearMessages() method on each error when the user clicks the back/previous link.
> Bug 7920 - Error messages not getting cleared when user goes back. 

- src/samples/UnAuthChildBenefitsClaim/deleteAnswers.tsx
- src/samples/UnAuthChildBenefitsClaim/index.tsx
As a part of these bug now we could able to generate the start claim again button with standard gov uk styling.
And we could able to remove confirmation screen appearing on delete answers screen.
> Bug 7961 & Bug 8028 Re-style the claim again button and fix the multi screens issue

- src/components/BaseComponents/FormGroup/FieldSet.tsx
The fieldset element has an aria-describedby attribute value of "undefined hint". I believe this is a wider issue for all fieldgroups, but this should be resolved by REACT team. If hint is not defined, then the attribute should not be included.
> BUG-7400: Fixed bug

- assets/i18n/cy.json
- assets/i18n/en.json
- src/components/override-sdk/infra/ActionButtons/ActionButtons.tsx
As per the latest discussion between PO's and BA's , we have a user story where we need to remove close claim button for all the Un-Auth screens.
Deleted the close claim button rendering code and also the constants related to text 'close claim' have been removed from both en.json and cy.json.
> US-12854 : Remove close claim button on all Un-Auth screens

- src/components/override-sdk/template/DefaultForm/DefaultForm.css
Below screens are having issue - 
- Remove your other last name or family name
- Confirm and remove nationality
- Confirm and remove partner nationality
- Confirm and remove country (after In the last 3 months, which countries have you worked in?)
- Confirm and remove country (after In the last 3 months, which countries did you receive benefits in?
- Confirm and remove country (after In the last 3 months, which countries has your partner worked in?
- Confirm and remove country (after In the last 3 months, which countries did your partner receive benefits in?
- Remove the child's other name
Here are few screenshots after fix - 
- Remove your other last name or family name
- Confirm and remove nationality
- Confirm and remove country (after In the last 3 months, which countries have you …
> fix: BUG-7914 - font size issue on 'remove' screens

- src/samples/ChildBenefitsClaim/ConfirmationPage.tsx
This Bug fix is regarding with confirmation screen , where for an Un-Auth claim we are getting case reference number appearing even when selected Do you have NINO as 'Yes'.
> Bug - 8050 : fix related to case reference number

- src/samples/StaticPages/AreYouSureToContinueWithoutSignIn/AreYouSureToContinueWithoutSignIn.tsx
- src/samples/StaticPages/ChooseClaimService/index.tsx
As a part of this Bug fix , we need to remove back button on page where claimant chooses the journey he want to enter.
Also this one got confirmed from jake and mashuk on triage call.
Also as a part of upcoming release , we are now pointing to MDTP Un-Auth instead of actual Un-Auth
> Bug-8132 : removal of back link in choose a claim service page

- src/components/override-sdk/infra/Assignment/Assignment.tsx
- src/components/override-sdk/template/DefaultForm/DefaultForm.tsx
Here I am attempting to get the correct location of the header title translations from the nested default form components. 
I'm adding a store value for the locale reference, then using a slight timeout to make sure the store is updated before attempting to retrieve the header translation.
> Bug 7113 - Getting the header translations from the default form locale reference

- src/components/AppComponents/SummaryPage/SummaryPage.tsx
- src/components/AppComponents/SummaryPage/index.tsx
- src/components/override-sdk/infra/Assignment/Assignment.tsx
- src/samples/ChildBenefitsClaim/ConfirmationPage.tsx
- src/samples/HighIncomeCase/index.tsx
- src/samples/HighIncomeCase/reuseables/PegaSetup.tsx
- webpack.config.js
Creates new 'Summary' Component to handle both confirmation and other 'end' screens for journeys.
This component will take a summary content block, which is parsed if html, a title and banner text.
If the component received banner text, it will display this in the green confirmation banner, followed by the content block,
otherwise it will display the title as plain h1, followed by the content block..
Also adds functionality to store the Case ID before closing a case, to allow fetching of summary page content on loading of the 'End page'
>  screen functionality for HICBC claims

- src/samples/UnAuthChildBenefitsClaim/index.tsx
Once the claim has been deleted , the claimant should not see the timeout pop up.
so , as a current fix , we are conditionally rendering the pop up.
> Bug - 8114 : Should not render the timeout modal once claimant encounter the delete answers screen

- src/components/templates/ClaimsList/index.tsx
Updated switch case for  'Resolved-Disallowance' to show CLAIM_RECEIVED status
> fix: added status 'Resolved-Disallowance' to show CLAIM_RECEIVED

- assets/i18n/cy.json
- assets/i18n/en.json
- src/components/AppComponents/TimeoutPopup/index.tsx
- src/components/AppComponents/TimeoutPopup/timeOutUtils.tsx
- src/samples/StaticPages/ChooseClaimService/index.tsx
- src/samples/UnAuthChildBenefitsClaim/index.tsx
These are the changes done according to the latest user story 12607 , where claimant will be having a timeout pop appearing on confirmation screen after submitting a claim.
Here claimant will be asked to either stay on same confirmation page or exit and go back to gov.uk page
> Us 12607 : new changes related to timeout pop on un-auth confirmation screen

- assets/i18n/cy.json
Here as a part of this Bug ticket , we need to replace existing english content with welsh content for cookies page.
> Bug - 8189 : Add missing welsh translations for cookies page

- assets/i18n/cy.json
- assets/i18n/en.json
- src/samples/StaticPages/ChooseClaimService/index.tsx
As a part of this Bug , we are adding missing welsh translations required for error messages on choose claim service and do you want to sign in pages.
> Bug-8166 : Welsh translation for static page error messages

- src/samples/ChildBenefitsClaim/ConfirmationPage.tsx
- src/samples/UnAuthChildBenefitsClaim/index.tsx
These changes are added around resolving the issue where the claim is getting deleted when we wait for entire timeout in confirmation page after the time out pop up appears.
> US-12607 : issue resolved around entire time out in confirmation page

- src/components/helpers/utils.ts
caseType is coming undefined when user land on tasklist which is 1st screen in unauth. So added check window.location.href.includes('/ua') to determine case is auth or unauth.
> BUG-8328 & 8326 - Fixed shuttering issue for unauth

- src/components/override-sdk/template/DefaultForm/DefaultForm.tsx
- src/samples/UnAuthChildBenefitsClaim/deleteAnswers.tsx
- src/samples/UnAuthChildBenefitsClaim/index.tsx
As a part of this PR , we are adding changes where when claimant refreshes any page in un-auth claim , 
he/she will be landed on delete claim screen.
Another scenario : When on delete claim screen, if refreshed , should show delete claim screen only.
Once claimant clicked start claim again , he/she should be able to progress with new claim again.
> US-12655 : Display delete claim screen when user refreshes a claim page in Un-Auth journey

- src/samples/ChildBenefitsClaim/index.tsx
- src/samples/UnAuthChildBenefitsClaim/index.tsx
As a part of this PR , we have included the changes to useEffect hooks in both auth and un-auth index.tsx pages, 
we included shutter service state variable in useEffect dependencies array , so it will call pageTitle when changed.
> Bug-8340 : page title not reflecting for shuttering service page

- src/samples/ChildBenefitsClaim/ConfirmationPage.tsx
- src/samples/ChildBenefitsClaim/index.tsx
- src/samples/UnAuthChildBenefitsClaim/index.tsx
As a part of this PR , we have provided fix for lock issue in AUI , when claimant clicked save and comeback later link.
Also we provided fix at the confirmation page after submission of entire claim , we are calling close container API after 2.5 seconds of rendering the confirmation page , so that it will be executed at very last.
> Bug - 8123 : Claim getting locked in AUI after claimant clicked on save and come back later

- src/components/BaseComponents/Autocomplete/Autocomplete.tsx
- src/components/BaseComponents/FormGroup/FieldSet.tsx
- src/components/override-sdk/field/AutoComplete/AutoComplete.tsx
**BUG-7400 - Address fields not grouped**
Issue: Missing fieldset and legend as address fields presented to screen reader users as separate fields without grouping. This will help SR users to identify how the page is structured.
Users presented visually with two separate groups of questions, however screen reader won't announce grouping of different sections without appropriate legend it makes hard for users to differentiate context of address fields.
Resolution: 
Wrapped address lookup fields in fieldset with additional legend
1. **BaseComponents/Autocomplete/Autocomplete.tsx** - Updated FormGroup element to FieldSet 
2. **FieldSet.tsx** -  Added Autocomplete element style condition
3. **override-sdk/field/AutoComplete/AutoComplete.tsx** - Assigned propName to id property when name is …
> BUG-7400 - Address fields not grouped

- src/components/custom-sdk/template/HMRC_ODX_GDSTaskListTemplate/index.tsx
- src/components/override-sdk/template/DefaultForm/DefaultForm.tsx
- src/samples/ChildBenefitsClaim/ConfirmationPage.tsx
- src/samples/UnAuthChildBenefitsClaim/deleteAnswers.tsx
- src/samples/UnAuthChildBenefitsClaim/index.tsx
Tested the below scenario
Refresh on:
TaskList - fresh case
Static pages - no impact
Assignments - land into same screen
CYA -land on same screen
Confirmation - fresh case
Delete screen - fresh case
Solution - saving the assignment id on browser refresh and navigating user to same screen when we found assignment id.
> US12655-1: Claimant will land on same screen on browser refresh

- src/samples/ChildBenefitsClaim/index.tsx
This is to fix the bug where the user portal is showing when a user starts a new claim. I've added a check to see if the "assignmentPConn" isn't it's default value (null) as it's populated when a user is in the assignment. Because I've added a little more complexity to the async function (line 243) I've put it in a try, catch block.
> Bug 8302 user portal displaying on new claim

- src/components/override-sdk/infra/Assignment/Assignment.tsx
**BUG-6776 Error summary is not in sequence at top**
**Issue:** Error messages at the top of the screen (Error summary) are not in the sequence order.
**Resolution:** 
1. **Assignment.tsx** - Added sorting to error message summary based on form field sequence.
> BUG-6776 Error summary is not in sequence at top

- src/samples/UnAuthChildBenefitsClaim/deleteAnswers.tsx
As a part of this PR , we fixed delete screen issue on entire timeout by removing the session storage items.
> US-12655 : Issue around delete screen appearing for entier timeout is fixed

- src/components/override-sdk/infra/Assignment/Assignment.tsx
**BUG-7756(Incorrect error message and Back button issue)**
The fix is about for allowing back button click when there is invalid date(it means if the user leave any one value of MM, DD, or YYYY as empty or  invalid value). Because the Pega API is expecting valid date or empty date. 
Now we clear the date value if there is invalid date and allowing back button click. 
**Assignment.tsx**: New method added in back link action. It will check only on date component with click action and clears the date value if there is invalid date.
> Bug 7756 - Incorrect error message and Back button issue

- assets/i18n/en.json
- src/components/override-sdk/infra/Assignment/Assignment.tsx
- src/samples/AppSelector/index.tsx
- src/samples/HighIncomeCase/ClaimPage.tsx
Due to recent changes to logout logic, which now needs to redirect to the Gov Gateway signout url, the 'back' buttons on the first page or Summary pages no longer returns the user to the landing page. 
This change is a short term fix to reword the back links to better reflect what will happen for the user, until expected redirection can be handled.
> BUG-8418 - Update backlink text to reflect that user will be logged out

- sdk-local-component-map.js
- src/components/override-sdk/field/RichText/RichText.tsx
- src/components/override-sdk/field/RichText/index.tsx
- src/components/override-sdk/template/DefaultForm/DefaultForm.tsx
The bug is on the declaration screen. We have duplicate declaration text and warning (if the user has to send in documents i.e. adoption or born in another country).
Pega is using RichText fields for this content. Previously we were using the redux store to display these values in the correct place and with the correct styles I have removed this old code. 
Also the standard RichText pega component adds a lot of nesting to the text, and also a blank label tag, which isn't accessible.
So in this code I've created an override component for RichText which very simply passes the value (html) to the ParsedHtml component so it's displayed correctly. I've also added a check for a 'p' tag and if so add the 'govuk-body' class to the surrounding div so it has the correct styles.
> Bug 8265 - Duplicate declaration text and warning.

- src/components/override-sdk/field/AutoComplete/AutoComplete.tsx
The handlechange event of autocomplete was not working as expected when wrapped in main wrapper from pega. Because it was not able to get the id of autocomplete component. This fix is to address the issue
> BUG-7400 autocomplete in address field fix

- src/components/AppComponents/LanguageToggle/index.tsx
**_BUG-8232 -Language toggle issue#R_**
This issue is about the radio option is not getting translated when we toggle language to Welsh.
The issue is, the radio option content was present in the D_SCOPEDREFERENCEDATALISTBYTYPE.json but this json is not been called on loadlocalereferences of the toggle action. 
Now we have added this json in toggle action.(also verified this json was referred as datapage as table type in the assign worklist json response.)
> Bug 8232 - Language toggle issue#R

- src/components/BaseComponents/Autocomplete/Autocomplete.tsx
- src/components/override-sdk/infra/Assignment/Assignment.tsx
Currently the error summary component is missing the error(s) from any autocomplete fields as the error summary component hasn't re-rendered before the error checking has completed. I've added a publish event which we can subscribe to in the assignment component so that we can update the errors in the error summary once the re-render (and loading of the options list) is complete.
> Bug 8375 - Error summary not showing autocomplete field errors. 

- src/samples/HighIncomeCase/ClaimPage.tsx
- src/samples/HighIncomeCase/LandingPage.tsx
- src/samples/HighIncomeCase/index.tsx
- src/samples/HighIncomeCase/reuseables/AppContext.ts
Reverts 'enabling' of Language toggle for HICBC claim as we are not yet ready for translations.
Adds handling of a SDK-config item for future toggling on/off of the feature. (Will remained toggled off if the SDK config item is not present)
> Reverts Language toggle 'set up' for HICBC claims and adds sdk config 'approach' to toggle back on in future

- constellation-comp-config/tsconfig.build.json
- src/samples/HighIncomeCase/reuseables/AppContext.ts
- tsconfig.build.json
Added required HICBC AppContext file to tsconfig files and fixed a minor TypeScript issue in the file to allow for DXCB build and publish of custom/overriden DX components.
> Fix required to ensure integrated DXCB can continue to build and publish custom/overriden DX components

- src/samples/ChildBenefitsClaim/index.tsx
- src/samples/StaticPages/ErrorSummary/index.tsx
As a part of this PR we have fixed the issue around the heading of the error at summary level of static pages.
Before we are not getting welsh content , so now we are getting welsh upon clicking choice of welsh at top of the page.
> US-13377 : Addressing BA review comments for welsh content for error heading

- src/samples/ChildBenefitsClaim/ConfirmationPage.tsx
This PR fixes the issues around appearing of reference number on confirmation page even if claimant entered NINO.
Also it fixes the issue where after reload of confirmation page , claimant is seeing reference number for NINO provided.
> Bug-8588 : Issue around reference number on confirmation page

- src/components/override-sdk/infra/Assignment/Assignment.tsx
As a part of this PR we have fixed the issue when there are multiple errors on fields like text box , and if the screens are in welsh , the error messages were not getting converted to welsh completely.
> Bug - 8486 : Resolved issue around error at summary level 

- src/components/custom-sdk/template/HMRC_ODX_GDSSummaryCard/index.tsx
- src/components/override-sdk/infra/View/View.tsx
As a part of this PR we have fixed an accessibility issue where empty html h2 elements are being rendered on multiple pages.
> Bug-8770-8771 : Empty h2 elements are being rendered on multiple pages

- src/components/AppComponents/TimeoutPopup/index.tsx
- src/samples/ChildBenefitsClaim/index.tsx
The bug is that the countdown timer doesn't reach '0' before sign out on the declaration screen. By using the 'signoutHandler' to sign out after the countdown is completed you can now see '0' in the countdown before the app signs out. I've also removed the 'signoutTimeout' functionality as this isn't being used anymore.
> Bug 8785 Timeout counter - 0 Sec not counted

- src/components/AppComponents/SummaryPage/SummaryPage.tsx
- src/components/override-sdk/template/SimpleTableManual/SimpleTableManual.tsx
- src/samples/HighIncomeCase/ClaimPage.tsx
Extends SimpleList component to handle 'special case' of Instruction text, driven by the content value (which should be standardised on Pega side)
Extends logic for fetching SummaryPage content, and to switch between different language content.
> Translatable Summary Pages and Instruction Text 

- src/components/AppComponents/LanguageToggle/index.tsx
- src/components/override-sdk/field/Date/Date.tsx
Updates date component with an inline change link to display long form date format  (e.g '4 March 2024')
Also hooks dayjs into language change logic to ensure that that long form date display reflects current selected language.
> US-14729 - Read only dates in long format reflect selected user language

- src/samples/ChildBenefitsClaim/index.tsx
We are hiding the pega root div with CSS in non pega environment as we can not add conditional rending to pega root div on start.
> BUG-8881: Fixed question flickering issue on portal

- src/components/override-sdk/infra/Assignment/Assignment.tsx
I've added the toggleNotificationProcess so that when a user starts or opens an existing claim it runs once and sets the language for the emails and texts. This means if a user starts a claim in English, saves it for later, then changes the language to Welsh for example, then finishes the claim the text and email will be in Welsh.
> BUG-8839 - E-mail & TxtMsg contents are not showing in welsh

- assets/i18n/cy.json
- assets/i18n/en.json
- src/samples/ChildBenefitHub/ChildBenefitHub.tsx
- src/samples/ProofOfEntitlement/ProofOfEntitlement.tsx
Add the timeout functionality to the 'View Proof Entitlement' and ChB Hub pages to ensure that users security is upheld but automatically logging them out after certain time of inactivity.
Reuses the existing Timeout component
However, have tried using 'PCore.getUserApi().getOperatorDetails(PCore.getEnvironmentInfo().getOperatorIdentifier());' as the service keep-alive. - This is to avoid using application specific data pages. This call appears to make an api call each time so expecting this will work reliably.
> US-14920 - View PoE page and ChB Hub - Time out

- src/components/AppComponents/SummaryPage/SummaryPage.tsx
- src/samples/EducationStart/ClaimList.tsx
- src/samples/EducationStart/Landing.tsx
- src/samples/EducationStart/PortalPage.tsx
- src/samples/EducationStart/index.tsx
This PR consist Portal page preconditions - 
- Default call will load inprogress and submitted cases, if no case available then default to Start claim page
- If a claimant clicks on Save and come back later button in any stage of request, they will be redirected to portal page
- Portal page will then show a banner- We saved your progress and will store your information for 28 days
- If a claimant has submitted the claim successfully (US-12980 & US-13510) and clicks on Tell us about another young person staying in approved education or training, they will be redirected to portal page.
- Claimants whose journey has ended and clicks on: ‘You can tell us about another young person’ (Refer US-12974/14276/ 14244/ 14245-AC4)o Will reach portal page
- Claimants whose journey has ended and clicks …
> feat: US-14607 Portal Conditioning

- src/components/custom-sdk/template/HMRC_ODX_GDSSummaryCard/index.tsx
I've re-factored the code as I needed to change the way it builds the hidden text for 'useType' 4 in the GDS Summary Card because the values in the pega store have changed slightly.
> Bug 8738 - hidden text showing wrong

- src/components/helpers/hooks/useTranslatedStaticPageError.ts
- src/samples/StaticPages/AreYouSureToContinueWithoutSignIn/AreYouSureToContinueWithoutSignIn.tsx
- src/samples/StaticPages/CheckOnClaim/index.tsx
- src/samples/StaticPages/ChooseClaimService/index.tsx
- src/samples/StaticPages/DoYouWantToSignIn/doYouWantToSignIn.tsx
Have added a custom hook to handle the error translations on the static pages if the user toggles the language after the error appears.
> Bug 8947 - Static pages error message not in welsh when toggled 

- src/components/override-sdk/field/RadioButtons/RadioButtons.tsx
**US-13000-1 (Education Start - Customer- Welsh Translation- All screens)**
This fix is for in some scenario(at more than one datasource), if not matching classname check then else part is taking data source to get localreference logic for radiooption.
This fix will work for one chb page as well.
> US-13000-1 (Education Start - Customer- Welsh Translation- All screens)

- src/components/AppComponents/LanguageToggle/index.tsx
- src/components/custom-constellation/template/HMRC_ODX_sectionBased/demo.stories.tsx
- src/components/override-sdk/field/AutoComplete/AutoComplete.tsx
- src/components/override-sdk/infra/Assignment/Assignment.tsx
- src/components/override-sdk/infra/View/View.tsx
- src/components/override-sdk/template/DefaultForm/DefaultForm.tsx
- src/samples/ChildBenefitsClaim/index.tsx
- src/samples/EducationStart/reuseables/PegaSetup.tsx
- src/samples/HighIncomeCase/reuseables/PegaSetup.tsx
- src/samples/UnAuthChildBenefitsClaim/index.tsx
Extends Language Toggle functionality to store list of localeResources for each page as we navigate through a claim to try to ensure that all required bundles are loaded and used when toggling language
Updates Assignment and Default form component to use the Pconnect localization call rather than PCore localization call as this appears to respond 'better' to locale resource loading (avoiding issue we have sometimes seen where localeStore was not updated/populated at time of PCore localisation call.
This has allowed a simplified Assignment Heading logic, simply calling localisation inline.
Finally, have also updated error message localisation in Assignment component to fix issue with missing localeReference due to new localisation call.
Also removes locale resource load calls from …
> Bug-8814 Paragraphs Welsh language toggle issue ( + General Translation bug fixes - assignment headings) 

- src/samples/ProofOfEntitlement/ProofOfEntitlement.tsx
Updated requirements for Proof of Entitlement service no longer require NINO to be passed from front end as parameter to the getEntitlement datapage, so removing the passing of this parameter from the getDPage api call.
> US-16647 - Proof Entitlement getChBEntitlment DPage no longer needs NINO parameter

- src/samples/ProofOfEntitlement/ProofOfEntitlement.tsx
Data page returns 2 flags: hasAward and hasAccess.
hasAward is true IF the user has an active child benefit awarded and false if the award date is in the past.
hasAccess is true IF the end date is within 5 years of today and false if the end date is more than 5 years ago.
So using these flags we should show the entitlement if:
- User has an active child benefit
- If a User has had an active award in the last 5 years
Else the user should see this page:
> US-16776-1: display POE details for up to 5 years

- assets/css/print.scss
When in high contrast mode, users are seeing yellow logos which is not an accessible colour. There is no change when the high contrast is off.
> BUG-9747: set the logo to not a link when the high contrast mode is on

- src/samples/ProofOfEntitlement/ProofOfEntitlement.tsx
We have wrapped the loading page in a Main.
The skip to content accessible link works correctly too
> US-9595: wrap loading page with main
