norm-l/odx

src/components/BaseComponents/TextInput/TextInput.tsx
src/components/forms/Email/index.tsx
src/components/forms/Phone/index.tsx
src/components/forms/TextInput/index.tsx

Fixes linting issues blocking build of these changes

Text input component - fixing linting issues

---

src/components/BaseComponents/FormGroup/FormGroup.tsx
src/components/BaseComponents/Select/Select.tsx
src/components/BaseComponents/TextInput/TextInput.tsx
src/components/forms/Dropdown/index.tsx
src/components/forms/TextInput/index.tsx
src/helpers/hooks/QuestionDisplayHooks.ts
src/helpers/hooks/QuestionDisplayHooks.tsx

Implements a base Select component, which is implemented in the SDK Dropdown component.
Also refactors the 'form group' element out to a separate component, as this is reused between Select and Text input component.
(Refactored TextInput to use FormGroup component)
Also implements a hook to check if a field is the only field on the page, and to fetch the current step name, used to define the display of the field label.

Select component

---

src/components/forms/Dropdown/index.tsx

Passes name property to Dropdown component  to populate the required name, id and for attributes.

US-9355 - UX Review fix

---

src/components/ActionButtons/index.tsx
src/components/BaseComponents/Button/Button.tsx
src/components/templates/OneColumn/index.tsx

Updated the Button component as per GDS

Button component

---

src/applications/ChildBenefitsClaim/StartPage.tsx
src/applications/ChildBenefitsClaim/index.tsx
src/components/ActionButtons/index.tsx
src/components/Assignment/index.tsx
src/components/BaseComponents/Button/Button.tsx
src/components/BaseComponents/ErrorSummary/ErrorSummary.tsx

This PR contains the code for 
- Start Screen 
- Button component updated, to include start button component
- UX review fix for the submit popup - repurposed the error popup code to use the error Summary component that will be implemented in MVP2 US-9419

Start now screen

---

src/components/BaseComponents/TextInput/TextInput.tsx
src/components/forms/TextInput/index.tsx

(BUG-5840)
Textbox width is not based upon the number of characters
Logic has been set for different widths of textbox as per different number of characters. Can be tested once we get maxLength form Pega side

Text input width fix

---

src/components/templates/DefaultForm/index.tsx

Fixes observed issue with labels on conditionally displayed fields

Label fixes pm - Resolves recently observed issue

---

package.json
src/components/BaseComponents/FormGroup/FormGroup.tsx
src/components/BaseComponents/TextInput/TextInput.tsx
src/components/forms/TextInput/index.tsx

Bug
(BUG-5886)
Where do you live page are not accessibility complaint -> unique id's has been assigned to each text input fields

Fix for address field accessibility

---

src/components/ActionButtons/index.tsx
src/components/BaseComponents/Checkboxes/Checkbox.tsx
src/components/BaseComponents/Checkboxes/Checkboxes.tsx
src/components/forms/Checkbox/index.tsx
tests/unit/components/BaseComponents/Checkboxes.test.tsx
tests/unit/components/BaseComponents/__snapshots__/Checkboxes.test.tsx.snap
tests/unit/components/BaseComponents/__snapshots__/DateInput.test.tsx.snap
tests/unit/components/BaseComponents/__snapshots__/TextInput.test.tsx.snap

2 fixes are addressed in this PR
- Checkbox validation while submitting a claim acts as expected, throws error if checkbox is not clicked.
- Story comments on checkbox required it to be standard size, that is fixed

Submit claim no error

---

src/applications/ChildBenefitsClaim/ConfirmationPage.tsx

Bug
(BUG-5960) - Confirmation page is not accessibility complaint

confirmation Page Accessibility Issue Fix

---

src/components/templates/Details/index.tsx

Bug
(BUG-5990)
Partner Name & DOB page is not accessibility complaint

Fix for partners page accessibility issue'

---

src/components/Assignment/index.tsx
src/index.html
tests/unit/components/BaseComponents/__snapshots__/Checkboxes.test.tsx.snap

(BUG-6077) - Buttons, Radios to be clicked twice - fixed

radio button click issue fix

---

src/bridge/react_pconnect.jsx

TASK 25560 - RichText mapping with textinput(part of story US-9455)

RichText mapping with textinput

---

src/components/BaseComponents/DateInput/DateInput.tsx
src/components/BaseComponents/FormGroup/FieldSet.tsx
src/components/BaseComponents/FormGroup/FormGroup.tsx
src/components/forms/ChangeLink/index.tsx
src/components/forms/Checkbox/index.tsx
src/components/forms/Date/index.tsx
src/components/forms/RadioButtons/index.tsx
src/components/forms/TextInput/index.tsx
tests/unit/components/BaseComponents/__snapshots__/Checkboxes.test.tsx.snap
tests/unit/components/BaseComponents/__snapshots__/DateInput.test.tsx.snap

Passes testId values to form groups, fieldsets and checklink components to enable automated testing.

US-9775 Propogate Test IDs to DOM

---

src/components/Assignment/index.tsx

- added scroll to Top on Continue and Previous buttonPress

scroll to top added

---

src/components/BaseComponents/TextInput/TextInput.tsx
src/components/forms/TextInput/index.tsx
tests/unit/components/BaseComponents/__snapshots__/DateInput.test.tsx.snap

Task
(TASK-25648-1) - Addresss Lookup API call onBlur of postcode field in what is your POST CODE page

AddressLookup API Call from react

---

src/bridge/react_pconnect.jsx
src/components/ActionButtons/index.tsx
src/components/Assignment/index.tsx
src/components/BaseComponents/BackLink/BackLink.tsx

US-9655
Apply - Claimant - Back link to navigate to a previous page

BackLink Feature

---

src/components/Assignment/index.tsx
src/components/BaseComponents/BackLink/BackLink.tsx
tests/unit/components/BaseComponents/__snapshots__/Checkboxes.test.tsx.snap

(BUG-6220)
Page focus to screen header which is hiding Back link

BUG-6220 fix

---

src/components/Assignment/index.tsx
src/helpers/hooks/QuestionDisplayHooks.ts

useIsOnlyField() hook set to always return false so we can treat all pages as multi question pages.

useIsOnlyField logic removed, set to always false

---

src/components/BaseComponents/TextInput/TextInput.tsx
src/components/forms/TextInput/index.tsx

Added disabled prop to Input box

disabled prop added to input box

---

src/components/forms/Group/index.tsx

instruction text component added to Group

bug 6320 fixed

---

src/components/forms/Group/index.tsx

fix added : checkbox error handling reflecting in group

---

src/components/BaseComponents/TextInput/TextInput.tsx
src/components/forms/TextInput/index.tsx

maxLength limit removed from text input fields

---

assets/css/appStyles.scss
package-lock.json
package.json
src/index.html
webpack.config.js

Adds url-loader to allow our app styles .scss to successfully build.
Removes static references to govuk-frontend and appStyles in index.html

Fixes app style scss building

---

package.json
src/components/Assignment/index.tsx
src/components/templates/ClaimsList/index.tsx
src/helpers/authManager.js
src/helpers/utils.ts
src/index.html

- Service header and Sign out navlink added to the navbar
- Sign out link logs the user out and redirects to the required link

Us 10029 and 9829

---

src/components/View/index.tsx
src/components/templates/MimicASentence/config.json
src/components/templates/MimicASentence/index.tsx

New template added to enable read-only display of multiple properties in a single string.

BUG-6603 - Added new custom DX template Mimic A Sentence

---

assets/i18n/cy.json
src/applications/ChildBenefitsClaim/UserPortal.tsx
src/components/templates/ClaimsList/index.tsx

BUG-6492 - Portal - "Ask HMRC online" added the hyper link that opens in a new tab
BUG-6681 - Removed <A> wrapper from the Childs name in the claims list
BUG-6677 - Added Welsh language translation for Date fields labels (Day, Month, Year)

Fixes for BUG-6492 BUG-6681 BUG-6677

---

assets/i18n/cy.json
assets/i18n/en.json
package.json
src/components/BaseComponents/Modal/Modal.tsx
src/components/forms/LogoutPopup/index.tsx

User Story
(US-9916-1)
1st Claim - Claimant - Sign Out of Claim Journey -> Accessibility fixes

Us 9916 1 accessibility fixes

---

src/components/helpers/hooks/QuestionDisplayHooks.ts
src/components/override-sdk/field/Checkbox/Checkbox.tsx
src/components/override-sdk/field/Date/Date.tsx
src/components/override-sdk/field/Dropdown/Dropdown.tsx
src/components/override-sdk/field/RadioButtons/RadioButtons.tsx
src/components/override-sdk/field/TextInput/TextInput.tsx
src/components/override-sdk/infra/Assignment/Assignment.tsx
src/components/override-sdk/template/DefaultForm/DefaultForm.tsx
src/components/override-sdk/template/FieldGroupTemplate/FieldGroupTemplate.tsx

Revert "bug 6329 : Hide page label bug"

---

src/components/override-sdk/field/RadioButtons/RadioButtons.tsx

Revert "Removing unused isOnlyField"

---

src/components/override-sdk/field/Checkbox/Checkbox.tsx
src/components/override-sdk/field/Dropdown/Dropdown.tsx

Revert "Removing unused is only field"

---

assets/i18n/cy.json
assets/i18n/en.json
src/components/custom-sdk/template/HMRC_ODX_GDSInfoPanel/config.json
src/components/custom-sdk/template/HMRC_ODX_GDSInfoPanel/index.tsx

Minor update to the text - updating references of "Information" to "Important"

US-10435 - GDS Info panel updating text for important panel

---

src/components/override-sdk/infra/FlowContainer/FlowContainer.tsx

Applies hotfix to allow users to open cases not assigned to them to the FlowContainer component

BUG-6496 - Adds hasAssignments hotfix to FlowContainer

---

src/components/AppComponents/AppFooter/index.tsx

Updated 'Is this page not working properly' link to be dynamic based on environment config.  This is now strutured as per the AC
- NO PEGA DEPENDENCY

US 10837 - Updated 'Is this page not working properly' link

---

assets/i18n/cy.json
assets/i18n/en.json
src/samples/ChildBenefitsClaim/ConfirmationPage.tsx

US-11063 : reworded Resolution screen banner text

---

assets/i18n/cy.json
assets/i18n/en.json
src/samples/ChildBenefitsClaim/UserPortal.tsx

US-11188 : added a line 'We may call you...' to user portal page

---

assets/css/appStyles.scss
src/components/BaseComponents/TextInput/TextInput.tsx
src/components/override-sdk/template/DefaultForm/DefaultForm.tsx

Bug-7044 : gap added after address

---

assets/i18n/cy.json
assets/i18n/en.json
src/components/BaseComponents/NotificationBanner/NotificationBanner.tsx
src/components/custom-sdk/template/HMRC_ODX_GDSSummaryCard/index.tsx

BUG-7033 - Remove child_No warning message

Bug 7033 remove child issue

---

src/components/AppComponents/AppFooter/index.tsx
src/components/override-sdk/infra/Assignment/Assignment.tsx
src/samples/ChildBenefitsClaim/UserPortal.tsx

Not yet required to merge

---

assets/i18n/cy.json
assets/i18n/en.json
src/components/AppComponents/ServiceNotAvailable/index.tsx
src/samples/ChildBenefitsClaim/index.tsx

US-10099- NPS - System - NPS Service not available(React Config)

US-10099-Service not available react config

---

assets/css/appStyles.scss
src/components/helpers/formatters/ConditionalWrapper.ts
src/components/helpers/formatters/ConditionalWrapper.tsx
src/components/override-sdk/template/DefaultForm/DefaultForm.tsx
src/components/override-sdk/template/Details/Details.tsx

This change reworks the logic for <dl> wrapping within DefaultForm, to avoid double wrapping AND to avoid invalid elements with the the <dl>s (mainly the view labels) 
This change standardizes the visual display on the page, and also stops and invalid html, but introduces extra <dl>'s which are accepted as a slight accessibility impact. (hopefully to be resolved with reworking of CYA page)
-Adds some css to improve visual display of the page.

Bug-7232 CYA Alignment

---

src/components/BaseComponents/DateInput/DateInput.tsx
src/components/override-sdk/infra/Assignment/Assignment.tsx

U - Error summary link doesn't link to correct date field

BUG-6713 changes

---

src/components/AppComponents/ServiceNotAvailable/index.tsx

Bug 7344 : 'Is page not working?' link added to NPS failure page

---

src/components/BaseComponents/FormGroup/FieldSet.tsx
src/components/override-sdk/field/Checkbox/Checkbox.tsx
src/components/override-sdk/field/Date/Date.tsx
src/components/override-sdk/field/RadioButtons/RadioButtons.tsx
src/components/override-sdk/field/TextInput/TextInput.tsx

(BUG-7307)
A - Misleading errors (AA)

BUG-7307 - A - Misleading errors (AA) 

---

assets/css/appStyles.scss

Added custom style to align html content

BUG-7049-Aligning-HTML-Content-On-Confirmation-Page

---

src/samples/ChildBenefitsClaim/ConfirmationPage.tsx
src/samples/ChildBenefitsClaim/index.tsx

- in ChildBenefitsClaim/index.tsx , retrieved the caseID in a local state before assignment is finished/closed and passed it to Resolution screen.

Bug 7411 : Resolution screen missing

---

assets/i18n/cy.json
assets/i18n/en.json
src/samples/ChildBenefitsClaim/StartPage.tsx

Changed the h1 on Start Page to "Begin new Child Benefit claim"

Bug-7287 : added new h1 to StartPage

---

src/components/override-sdk/infra/ActionButtons/ActionButtons.tsx
src/components/override-sdk/infra/Assignment/Assignment.tsx

Added the scroll to top functionality to the cancel and save actions in order to match the "finishAssignment" action.

Bug 7214 - Scroll to top added to cancel button and save button.

---

assets/i18n/cy.json
assets/i18n/en.json
src/samples/ChildBenefitsClaim/index.tsx

- 'back' button works now
- page header changed as below

Bug 7428 : Start page header and back button fixed

---

assets/i18n/cy.json
assets/i18n/en.json
src/components/AppComponents/ShutterServicePage/index.tsx
src/samples/ChildBenefitsClaim/index.tsx

US-11302 -> Tech - Service Owner - Shutter Service Toggle

US-11302 -> shutter service toggle

---

src/components/BaseComponents/FormGroup/FieldSet.tsx
src/components/BaseComponents/FormGroup/FormGroup.tsx
src/components/override-sdk/template/DefaultForm/DefaultForm.tsx

Bug 7420 : Duplicate label removed

---

src/samples/ChildBenefitsClaim/index.tsx

Creating test branch to verify that no other issues arise from this change.

BUG-7411 Reorder display resolution screen call

---

src/components/override-sdk/template/DefaultForm/DefaultForm.tsx

Closed the open container when user closed browser

Bug 7479 - Continue Claim not working when user closes the browser in between journey

---

assets/css/appStyles.scss
assets/i18n/cy.json
assets/i18n/en.json
src/components/BaseComponents/NotificationBanner/NotificationBanner.tsx
src/components/BaseComponents/WarningText/WarningText.tsx
src/components/custom-sdk/template/HMRC_ODX_GDSSummaryCard/index.tsx
src/components/templates/ClaimsList/index.tsx
src/samples/ChildBenefitsClaim/UserPortal.tsx
src/samples/ChildBenefitsClaim/index.tsx

Added a warning text and notification banner to inform the claimant about how long their in-progress claims or data will be stored.

US-11235 -Claimant - Apply - Enhance the saved your data message

---

src/samples/ChildBenefitsClaim/index.tsx

I've added a useEffect to reset the timeout on view render to reset it in between screens.

Bug 7469 - Timeout issue

---

src/components/override-sdk/template/DefaultForm/DefaultForm.tsx

I've added a flag check before setting the declaration fields.

BUG-7438 - Declaration text showing on cases where it isn't required

---

src/components/override-sdk/template/FieldGroupTemplate/FieldGroupTemplate.tsx

Changed the default value to false from blank on change handler

Bug 7464 - Fixed checkbox bug

---

src/components/override-sdk/template/FieldGroupTemplate/FieldGroupTemplate.tsx

BUG 7464- Fixed type error

---

src/components/override-sdk/template/DefaultForm/DefaultForm.tsx

Revert "fix(Bug-7420 : fixed the issue around page heading on bank details sc…"

---

src/components/override-sdk/template/FieldGroupTemplate/FieldGroupTemplate.tsx

Added exclusive or option on what other benefits you receive question by refactoring code so that we can handle multiple questions.

US-10233: Added exclusive or option on what other benefits you receive question

---

src/components/helpers/constants.tsx
src/components/helpers/formatters/DateErrorFormatter.js
src/components/override-sdk/field/Date/Date.tsx

Added check for complicated date of birth property.
Added new constant file.
Also fix issue-126.

Issue-128: Fixed error message for date of birth

---

src/components/templates/ClaimsList/index.tsx

Added Pending-Disallowance status to claim received

BUG-7629: Added Pending-Disallowance status to claim received

---

src/components/helpers/utils.ts

fix: BUG-7599 - Shuttering

---

src/components/helpers/hooks/useServiceShuttered.ts
src/components/helpers/utils.ts
src/components/override-sdk/infra/Assignment/Assignment.tsx
src/components/templates/ClaimsList/index.tsx
src/samples/ChildBenefitsClaim/ConfirmationPage.tsx
src/samples/ChildBenefitsClaim/StartPage.tsx
src/samples/ChildBenefitsClaim/index.tsx

fix: BUG-7599

---

assets/css/appStyles.scss

The Colour highlighted on In Progress and Claim Received has been changed to blue. it has now been updated to the correct value.

BUG-7614 fixed background colour

---

assets/css/appStyles.scss

Removed unauth changes for colour & font and updated drop down legend to show as label

BUG-7616 updated styling for dropdown

---

src/components/BaseComponents/FormGroup/FormGroup.tsx

This is a PR to correct some GDS compliance issues. It's utilising the same context functionality in "DefaultFormContext".

US-11083 - Add instruction text handling for single question page Form Groups

---

assets/i18n/cy.json
assets/i18n/en.json
src/samples/ChildBenefitsClaim/ConfirmationPage.tsx
src/samples/UnAuthChildBenefitsClaim/index.tsx

Added new feature to Un-Auth journey , where we will have confirmation screen at the end that claim got submitted.
Another condition that is been added to conf screen is that user will shown with application reference number (which is case id) , if he selected "No" for the question NINO present.

US-12118 : user story for having a confirmation screen and also condition that ref number to be displayed when NO - NINO

---

src/components/helpers/constants.tsx
src/components/helpers/formatters/DateErrorFormatter.js

Removed logic to use prop name in error message when prop name have ? mark

BUG-7756: Fixed error message for date of birth

---

assets/i18n/cy.json
assets/i18n/en.json
src/components/BaseComponents/Autocomplete/Autocomplete.tsx
src/components/helpers/formatters/DateErrorFormatter.js

Added generic message for all the date field

Bug:7756 - Fixed DOB error message

---

src/samples/ChildBenefitsClaim/AccessibilityPage/index.tsx

Added . to fix bug on accessibility story

Bug:7769 - Fixed accessibility issue

---

assets/i18n/cy.json
assets/i18n/en.json
src/samples/AppSelector/index.tsx
src/samples/StaticPages/CheckOnClaim/index.tsx
src/samples/StaticPages/ChooseClaimService/index.tsx

This PR is for building the static screen where user selects check on claim in make a claim choice in US-10388.
The respective links provided in the content will redirect the user to corresponding pages.
welsh translation is provided.
back link is provided.

US-12243 : Static screen for check on claim

---

src/components/custom-sdk/field/HMRC_ODX_ComplexQuestionExplanation/index.tsx
src/components/override-sdk/template/DefaultForm/DefaultFormUtils.tsx

Removing the inset bar when it contains no text.

Testing blank inset bar

---

src/components/BaseComponents/Autocomplete/Autocomplete.tsx
src/components/override-sdk/field/AutoComplete/AutoComplete.tsx

Added condition on onload of dynamic script to fix loading issue

Bug-7864: Fixed autocomplete rendering issue for 1st time

---

src/components/BaseComponents/TextInput/TextInput.tsx
src/components/override-sdk/field/TextInput/TextInput.tsx

Setting Autocomplete attribute default to **off** if it is not getting set from Pega

fix: BUG-7816 - Autocomplete attribute

---

src/samples/AppSelector/index.tsx

The Routes corresponding to the static pages are being disabled until post live deployment.
So commented out the respective routes.

Disabling static page routes

---

src/samples/ChildBenefitsClaim/index.tsx

Blocked start now button for 30 sec so it wont clicked twice within 30 seconds.
Note for Akhila/Mody - add new key "secondsTillStartNowUnblocked" along with others like below in sdk-config.json manually 
"timeoutConfig": {
"secondsTilWarning": 780,
"secondsTilLogoug": 115,
"secondsTillStartNowUnblocked": 30
},

Bug-7906: Blocked start now button for 30 sec

---

assets/i18n/cy.json
assets/i18n/en.json
src/components/AppComponents/AppHeader/index.tsx
src/samples/ChildBenefitsClaim/ConfirmationPage.tsx

As per the UX review , Alex suggested some new changes to be added on confirmation screen.
POs also approved for the changes. So this PR is related with those changes.

Bug 7847 -- exit survey page changes

---

src/components/override-sdk/field/AutoComplete/AutoComplete.tsx

BUG-7911 -> Country field on What is the address? screen should be mandatory
BUG-7888 -> No error validation on Nationality Change link

BUG-7911 and BUG-7888

---

src/samples/ChildBenefitsClaim/ConfirmationPage.tsx

Added unauth check for reference number

BUG-8040: Added unauth check for reference number

---

src/samples/ChildBenefitsClaim/index.tsx

Added service not available check on top. Tested with Sutter service down also.

BUG-8032: Fixed service not available bug

---

assets/i18n/cy.json
assets/i18n/en.json
src/samples/ChildBenefitsClaim/ConfirmationPage.tsx

us-12512 - ux review comments addressed

---

src/components/override-sdk/field/Checkbox/Checkbox.tsx

Fixed provided for checkbox related scenario, below are the screenshots after fixing.

fix: BUG-8126 Duplicate error message for checkboxes

---

src/components/BaseComponents/Select/Select.tsx
src/components/helpers/utils.ts

As a part of this PR we need to display label for select address dropdown , which we replaced with field set component before.

Bug 8108 : Need to have label in the form for choose address

---

assets/css/appStyles.scss
src/samples/StaticPages/AreYouSureToContinueWithoutSignIn/AreYouSureToContinueWithoutSignIn.tsx
src/samples/StaticPages/ChooseClaimService/index.tsx

As a part of this PR , we have resolved issues around forms, errors, redirections , spacing issues.

Addressing of UX review comments from alex

---

src/samples/StaticPages/CheckOnClaim/index.tsx

**Must to go live**
we developed as per user story but during PO review, they figure out we need to remove MDTP url as it will be decommission today.

US-12243: Removed MDTP URL

---

assets/i18n/cy.json
assets/i18n/en.json
src/samples/StaticPages/ChooseClaimService/index.tsx

New story created for this change which need to go live today.
Added notification banner for static page

US-13374-1:Added notification banner for static page

---

assets/i18n/cy.json
assets/i18n/en.json
src/samples/StaticPages/ChooseClaimService/index.tsx

Revert "US-13374-1:Added notification banner for static page"

---

src/components/AppComponents/SummaryPage/SummaryPage.tsx
src/components/helpers/setPageTitleHelpers.ts
src/components/override-sdk/field/Date/Date.tsx
src/samples/HighIncomeCase/ClaimPage.tsx
src/samples/HighIncomeCase/LandingPage.tsx
src/samples/HighIncomeCase/index.tsx

Updates Date Field to localise error messages
Update SetPageTitle to accept alternate service name and call this across required pages

Bugs 8204 and 8200 - Page Title setting and Date Field error localisation

---

assets/css/appStyles.scss

Addition of minor CSS change to support tactical workaround in order to display headers and field labels correctly.

US-13235 - confirm payment details screen work 

---

package.json
src/components/AppComponents/TimeoutPopup/timeOutUtils.tsx
src/components/helpers/hooks/HMRCExternalLinks.ts
src/components/helpers/utils.ts
src/samples/ChildBenefitsClaim/index.tsx
src/samples/TopLevelApp/index.tsx
src/samples/UnAuthChildBenefitsClaim/index.tsx

Prod -  User clicks Back button from Sign in screen and gets stuck
- @pega/auth version updated to 0.2.8
- imports updated as per reference provided by Product team (https://github.com/pegasystems/react-sdk/commit/b21ae4cca8da56c1fffe2bad2b269f3013156b84?diff=split&w=0),

chore: @pega/auth version updated, imports updated

---

src/components/override-sdk/infra/Assignment/Assignment.tsx

dependency added to update tasklist heading

fix: Incorrect screen header in Tasklist

---

src/components/custom-sdk/template/HMRC_ODX_GDSTaskListTemplate/index.tsx
src/components/helpers/utils.ts
src/samples/ChildBenefitsClaim/index.tsx
src/samples/UnAuthChildBenefitsClaim/index.tsx

Implemented shutter for unauth
publish events on task list click to implement shutter for auth and unauth

US-12042: Shutter for unauth

---

src/samples/StaticPages/AreYouSureToContinueWithoutSignIn/AreYouSureToContinueWithoutSignIn.tsx

Managed the routing through isUnauthRouteToPega flag of sdk config.

US-13342: Control go live for unauth

---

assets/i18n/cy.json
assets/i18n/en.json
src/components/AppComponents/LanguageToggle/index.tsx
src/components/BaseComponents/ErrorSummary/ErrorSummary.tsx
src/components/custom-sdk/field/ChangeLink/ChangeLink.tsx
src/components/override-sdk/infra/Assignment/Assignment.tsx
src/components/override-sdk/infra/View/View.tsx
src/components/templates/ClaimsList/index.tsx
src/samples/ChildBenefitsClaim/index.tsx
src/samples/UnAuthChildBenefitsClaim/index.tsx

1. **LanguageToggle\index.tsx**   - Declared new Pcore variable to store the toggled language value and locale reference value
2. **Assignment.tsx** -  Subscribed language toggle value and updated the title based on language .
3. **View.tsx** -  loaded LocaleResources based on language toggle
4. **ClaimsList\index.tsx** - Added language toggle dependency variable to reload the claimsList data. 
5. **ChildBenefitsClaim\index.tsx** - Subscribed language toggle value into state variable and pass it through ClaimsList component as props.

US-12634 Language toggle implementation

---

src/components/AppComponents/TimeoutPopup/timeOutUtils.tsx
src/components/helpers/utils.ts
src/samples/ChildBenefitsClaim/index.tsx
src/samples/UnAuthChildBenefitsClaim/index.tsx

1. Logout code moved to utils
2. Added code to get redirection URL to terminate the session 
3. Covered below logout scenarios for auth & unauth pages- 
- Clicked Sign out button from Header 
- Clicked Sign out button from Signout popup
- Clicked Sign out button from Timeout popup
- Clicked Sign out button from Auto logout if user is inactive

fix: BUG-7748 - Logout functionality

---

src/samples/StaticPages/AreYouSureToContinueWithoutSignIn/AreYouSureToContinueWithoutSignIn.tsx

Fixed unauth not loading from static pages when user come from timeout popup
Added window reload as URL is changing but automatic reload is not happening.

BUG-8345: Fixed unauth not loading from static pages

---

src/components/custom-sdk/template/HMRC_ODX_GDSTaskListTemplate/index.tsx
src/components/override-sdk/infra/Assignment/Assignment.tsx
src/components/override-sdk/template/DefaultForm/DefaultForm.tsx
src/samples/ChildBenefitsClaim/ConfirmationPage.tsx
src/samples/UnAuthChildBenefitsClaim/deleteAnswers.tsx
src/samples/UnAuthChildBenefitsClaim/index.tsx

Fixed refresh issue on tasklist, confirmation screenv and Delete screen.
User will land into same screen on browser refresh

US-12655-1: Fixed refresh issue on tasklist and confirmation screen

---

assets/i18n/cy.json
assets/i18n/en.json
src/samples/ChildBenefitsClaim/ConfirmationPage.tsx

As a part of this PR , we have fixed page title issue in confirmation page , also made sentence change according to the requirements provided.
Got the respective welsh content from Mallik , so included in this PR.

Bug-8047 & Bug-8334 : Add welsh content and fix page title in confirmation page

---

assets/i18n/cy.json
assets/i18n/en.json
src/components/helpers/utils.ts
src/components/override-sdk/infra/Assignment/Assignment.tsx
src/samples/ChildBenefitsClaim/index.tsx
src/samples/UnAuthChildBenefitsClaim/index.tsx

**BUG-8232 Language toggle issue**
1. **cy.json** - Updated text case
2. **en.json** - Updated text case
3.  **utils.ts** -  Cleared Session storage to reset language preferences 
4. **ChildBenefitsClaim/index.tsx** - Added servicename as dependency  to update the title. 
5. **UnAuthChildBenefitsClaim/index.tsx** - Added servicename as dependency  to update the title.

BUG-8232 Language toggle issue

---

src/components/AppComponents/TimeoutPopup/timeOutUtils.tsx
src/samples/UnAuthChildBenefitsClaim/index.tsx

Sent ping to pega to refresh token on stay sign in click

BUG-8369: Fixed lock issue on refresh

---

src/components/BaseComponents/Autocomplete/Autocomplete.tsx
src/components/BaseComponents/FormGroup/FieldSet.tsx

As a part of this PR , we have fixed heading issue around auto complete screen. which in-turn resolving the issue around page title of that autocomplete screens.

Bug 8374 : Heading and page title issue on autocomplete screen

---

src/components/BaseComponents/Button/Button.tsx
src/samples/ChildBenefitsClaim/StartPage.tsx
src/samples/ChildBenefitsClaim/index.tsx

Added disabled attributes to start now

BUG-7906: Added disabled attributes to start now

---

src/components/BaseComponents/Autocomplete/Autocomplete.tsx
src/components/BaseComponents/FormGroup/FormGroup.tsx

Autocomplete wrapped in formgroup and removed from fieldset.

BUG-7400 - Autocomplete wrapped in formgroup and removed from fieldset

---

src/components/AppComponents/SummaryPage/SummaryPage.tsx
src/samples/HighIncomeCase/ClaimPage.tsx
src/samples/HighIncomeCase/index.tsx

While the 'end session' logic is investigated and understood, back to start link backlinks will be removed from HICBC Opt In claim to avoid unexpected and confusing behavior for users.

US-14086 Revert 'back to start page'  backlinks in hicbc app

---

src/components/BaseComponents/Autocomplete/Autocomplete.tsx

Additional changes to fix accessibility issues in autocomplete component

BUG-7400-additionalChanges

---

src/components/override-sdk/infra/Assignment/Assignment.tsx
src/samples/ChildBenefitsClaim/index.tsx

Event 'assignmentFinished' is getting called infinite times from product package file 'react-sdk/src/components/override-sdk/infra/FlowContainer/FlowContainer.tsx'
Solution - added temporary flag to restrict multiple calls

fix: BUG-8438 - Temporary workaround to restrict infinite update calls

---

assets/i18n/cy.json
assets/i18n/en.json
src/samples/ChildBenefitsClaim/ConfirmationPage.tsx

Change to the number of days in the confirmation message. I've also changed the i18n key to reflect it, and updated the confirmation component.

US-13989 - Change of number of days in the confirmation message

---

src/components/custom-sdk/template/HMRC_ODX_GDSTaskListTemplate/index.tsx
src/samples/ChildBenefitsClaim/index.tsx

As per this PR , we have replaced html button component code with existing button component code in base components.
Also added an extra space after a comment which showed up in lint errors.

US-13291 : Addressing UI review comments

---

assets/i18n/en.json

Updates the HICBC Service name displayed in header.

Updates hicbc service name (Translation File Change Only)

---

src/components/BaseComponents/TextInput/TextInput.tsx

Corrected logical operation | | to &&  in the textInputClassesWithWidth function to ensure width is both defined and not null

BUG-8704-Fix width validation

---

src/samples/EducationStart/index.tsx

Added a feedback URL for Beta Banner on every page of the  Education start journey

US-13477-Beta Banner feedback URL

---

src/components/BaseComponents/FormGroup/FieldSet.tsx
src/samples/EducationStart/index.tsx

As a part of this PR , we have fixed issue where error at field level are not updating to welsh even if we have welsh content.

Bug-8489 : Field level error is not getting translated to welsh

---

src/components/BaseComponents/MainWrapper/index.tsx
src/components/BaseComponents/RadioButtons/RadioButtons.tsx
src/components/override-sdk/infra/Assignment/Assignment.tsx
src/samples/EducationStart/ClaimPage.tsx
src/samples/EducationStart/LandingPage.tsx
src/samples/EducationStart/index.tsx
src/samples/EducationStart/reuseables/AppContext1.ts
src/samples/EducationStart/reuseables/AppContextEducation.ts
src/samples/EducationStart/reuseables/PegaSetup.tsx

Updated pagenotworking URL in education start journey

US-13480-Page not working URL, US-12984 (Radio button hint)

---

src/components/override-sdk/template/SimpleTableManual/SimpleTableManual.tsx

hicbc changes

---

assets/i18n/cy.json
assets/i18n/en.json
src/components/override-sdk/template/SimpleTableManual/SimpleTableManual.tsx
src/samples/AppSelector/index.tsx
src/samples/ChildBenefitHub/ChildBenefitHub.tsx
src/samples/HighIncomeCase/reuseables/AppContext.ts
src/samples/ProofOfEntitlement/ProofOfEntitlement.tsx

Sets up the 
/home and /view-proof-entitlement endpoints for the application, with attempt to log in for each
/view-proof-entitlement page currently placeholder and will be implementing with US-10311
/home content has been implemented, with translations.

US-14580 - ChB Hub page and US-14634 ChB hub and View proof entitlement endpoints

---

src/components/custom-sdk/template/HMRC_ODX_GDSCheckAnswersPage/index.tsx

Focus was not on top when we land to question through change link.

BUG-8631: fixed focus issue

---

src/components/helpers/utils.ts
src/samples/EducationStart/index.tsx
src/samples/EducationStart/reuseables/PegaSetup.tsx

**US-14325 - Education Start - Service Unavailable/Shutter**
This is for having the shutter page when service is unavailable in Edu Start app.
I have made slight changes in common function shuttering call like checking the edustart journey then replacing the feature id by edutart.
Other changes similar like hicbc and chb

US-14325 - Education Start - Service Unavailable/Shutter

---

src/samples/EducationStart/index.tsx

**US-14738 - Education Start - Customer- Welsh Translation-Accessibility**
React changes for switch language action

US-14738 - Education Start - Customer- Welsh Translation-Accessibility

---

src/components/override-sdk/infra/Assignment/Assignment.tsx

Revert "BUG-8839 - E-mail & TxtMsg contents are not showing in welsh"

---

src/samples/AppSelector/index.tsx

Small change to i18n loading logic to avoid displaying flash of un translated content across applications.

BUG-8376, BUG-8377, BUG-8590 - Tweaks to i18n loading to avoid keys being displayed

---

src/components/override-sdk/infra/Assignment/Assignment.tsx
src/samples/EducationStart/reuseables/PegaSetup.tsx

US-13510 - confirmation page for pending manual verification
This is for having confirmation page our education start journey on the status of "Pending-ManualInvestigation".
This is temporary workaround until pega provide solution ready.

US-13510 - confirmation page for pending manual verification

---

src/components/helpers/utils.ts
src/samples/ProofOfEntitlement/ProofOfEntitlement.tsx

Added the currency formatter and fixed the observations on the spacing. 
Auto formatted the file

BUG 9006 - Currency formatting

---

src/samples/ChildBenefitHub/ChildBenefitHub.tsx

temporary fix provided for BUG-8996 (it is blocking US-14576-1)

Bug 8996 fix view POE page not loading on route change via <link> component

---

src/samples/EducationStart/index.tsx

BUG-9054(S2 US13510 Incorrect application confirmation page)
Provided the fix the href link was not working in confirmation page.

BUG-9054(S2 US13510 Incorrect application confirmation page)

---

src/samples/ChildBenefitHub/ChildBenefitHub.tsx
src/samples/ChildBenefitsClaim/index.tsx
src/samples/EducationStart/index.tsx
src/samples/FullPortal/index.tsx
src/samples/HighIncomeCase/ClaimPage.tsx
src/samples/ProofOfEntitlement/ProofOfEntitlement.tsx
src/samples/UnAuthChildBenefitsClaim/index.tsx

Updated navigation to 'replace' so that _?code_ entry which in history with the intended new url without ?code

fix: BUG-8180/INC-B17940

---

src/samples/EducationStart/StartClaim.tsx

Page should always scroll to top

fix: Scroll to top observation

---

assets/css/print.scss
assets/i18n/cy.json
assets/i18n/en.json
src/samples/ProofOfEntitlement/ProofOfEntitlement.tsx

- Us-14781 Download POE PDF
- US-15153: Update content for PoE
- Review Fix - Print view, added bit for spacing between the sections
- POE page - address mapping updated

Us-14781 Download POE PDF, US-15153: Update content for PoE

---

src/samples/EducationStart/ClaimList.tsx
src/samples/EducationStart/Landing.tsx
src/samples/EducationStart/PortalPage.tsx
src/samples/EducationStart/index.tsx

BUG-9016(S2 US14325 Service shutter issue on Edu star)
Added the shutter service check in submitted cases

BUG-9016(S2 US14325 Service shutter issue on Edu star)

---

assets/i18n/cy.json
src/components/override-sdk/template/SimpleTableManual/SimpleTableManual.tsx
src/samples/EducationStart/ClaimList.tsx
src/samples/EducationStart/Landing.tsx

US-13000-1(Education Start - Customer- Welsh Translation- All screens)
* Get the localised content for the text "Your eligible children" for the page - Tell the Child Benefit Office about a young person.
* And added the localised content for "status" and "action button" for portal page.

US-13000-1(Education Start - Customer- Welsh Translation- All screens)

---

assets/css/appStyles.scss
assets/i18n/cy.json
assets/i18n/en.json
src/components/helpers/LoadingSpinner/LoadingSpinner.tsx
src/samples/ProofOfEntitlement/ProofOfEntitlement.tsx

Implemented POE page loader
Updated Loader component with additional styling 
Commented out download PDF - shelved for next sprint for the discussion with PO

US-15256 - Implemented POE page loader

---

src/samples/EducationStart/ClaimList.tsx

Bug 9089(S3 Blank screen while logging into portal)
There was blank page when clicking "continue my case" button also received api error from lke case locked
Now made the page gets loaded only the api success in this scenario.

Bug 9089(S3 Blank screen while logging into portal)

---

src/samples/EducationStart/ClaimList.tsx
src/samples/EducationStart/index.tsx
src/samples/EducationStart/reuseables/PegaSetup.tsx

Bug 9164(beta banner in service unavailable)
Added the beta banner for servcie unavailable and styling fix by replacing br
Removed the unsubscribe events for assignment finished and added another  logic (like chb) for infinite calls of service unavailable page subscription

Bug 9164(beta banner in service unavailable)

---

assets/i18n/cy.json
assets/i18n/en.json
src/components/BaseComponents/GDSWarningText/WarningText.tsx
src/components/BaseComponents/MainWrapper/index.tsx
src/samples/AppSelector/index.tsx
src/samples/ChangeOfBank/ChangeOfBank.tsx
src/samples/ChangeOfBank/StartPage.tsx
src/samples/HighIncomeCase/ClaimPage.tsx
src/samples/ProofOfEntitlement/ProofOfEntitlement.tsx

US-14088 - Change of Bank Start Page, with authentication, signout and time out feature
Tidy up - HICBC and View POE - removed the static text content

US-14088 Change of Bank - Start page

---

src/samples/EducationStart/index.tsx
src/samples/EducationStart/reuseables/PegaSetup.tsx

US 14719(Education Start - Portal page-Request summary details)
In this PR, provided the back link action that will be back to portal page for submitted cases.

US 14719(Education Start - Portal page-Request summary details)

---

src/components/custom-sdk/template/HMRC_ODX_GDSCheckAnswersPage/index.tsx
src/components/helpers/utils.ts
src/components/override-sdk/field/AutoComplete/AutoComplete.tsx
src/components/override-sdk/infra/ActionButtons/ActionButtons.tsx
src/components/override-sdk/infra/Assignment/Assignment.tsx

Fixed backlink issue for journey other than CHB

US-14597: Fixed back link issue for other journey

---

assets/i18n/cy.json
assets/i18n/en.json
src/components/override-sdk/infra/ViewContainer/ViewContainer.jsx
src/samples/ChangeOfBank/ChangeOfBank.tsx

US-14111 - Change of Bank resolution screen

---

src/components/custom-sdk/template/HMRC_ODX_GDSTaskListTemplate/index.tsx
src/components/override-sdk/infra/ActionButtons/ActionButtons.tsx

Disabled button on 1st click to prevent double click

Bug-9245: Disabled button on double click 

---

src/components/custom-sdk/template/HMRC_ODX_GDSCheckAnswersPage/index.tsx
src/components/override-sdk/field/AutoComplete/AutoComplete.tsx

Fixed rendering issue of autocomplete - Added timeout as cya is getting rendered before session storage value updated
Removing session storage when value is blank

Bug-9270: Fixed rendering issue of autocomplete

---

src/components/override-sdk/infra/Assignment/Assignment.tsx

Fixed rendering issue for back button on child summary screen

BUG-9319: Fixed rendering issue for back button on child summary screen

---

src/components/override-sdk/infra/Assignment/Assignment.tsx

Clear error message on back press

BUG-9279: Clear error message on back press

---

assets/i18n/cy.json
assets/i18n/en.json

US-14613-2: Button copy change

---

assets/i18n/cy.json
assets/i18n/en.json
src/samples/ChangeOfBank/ChangeOfBank.tsx
src/samples/ChangeOfBank/StartPage.tsx

Update the Header for the Change of Bank flow.

US-14895: updated the header text for CoB

---

src/components/custom-sdk/template/HMRC_ODX_GDSCheckAnswersPage/index.tsx
src/components/override-sdk/infra/Assignment/Assignment.tsx
src/samples/EducationStart/ClaimList.tsx
src/samples/EducationStart/index.tsx

back button changes for education start

US-15637: back button changes for education start

---

assets/i18n/cy.json
assets/i18n/en.json
src/components/custom-sdk/template/HMRC_ODX_GDSCheckAnswersPage/index.tsx
src/components/override-sdk/infra/ActionButtons/ActionButtons.tsx
src/components/override-sdk/infra/Assignment/Assignment.tsx

Added button on interruption and declaration screen and handled its navigation
TODO - Refactoring the code with adding dependency to useEffect on check answer page and its unit test which we will do as part of enhancement

US-15542: Handle navigation on interruption page and declaration page

---

src/samples/ChangeOfBank/ChangeOfBank.tsx

To enable language toggling for notifications in change of bank journey, have added the Notification Language toggle process calls to the language toggle

US-14785 - Calls Language Switch Process for Change of Bank claims

---

src/components/AppComponents/TimeoutPopup/index.tsx
src/samples/UnAuthChildBenefitsClaim/index.tsx

Amends made to the code to only use the current time out utils.

Bug 9441 popup showing when user is active in the claim

---

src/components/AppComponents/TimeoutPopup/index.tsx
src/components/AppComponents/TimeoutPopup/timeOutUtils.tsx
src/components/helpers/constants.tsx
src/samples/ChangeOfBank/ChangeOfBank.tsx
src/samples/ChildBenefitsClaim/index.tsx
src/samples/EducationStart/reuseables/PegaSetup.tsx
src/samples/HighIncomeCase/reuseables/PegaSetup.tsx
src/samples/UnAuthChildBenefitsClaim/index.tsx

Bug ticket - Timeout added as part of different story but did not show after 13 minutes

BUG-9368: Add millisecondsTilSignout to the CoB timeout

---

assets/i18n/cy.json
assets/i18n/en.json
jest.config.js
src/components/BaseComponents/NotificationBanner/NotificationBanner.tsx
src/samples/ChildBenefitsClaim/ExistingInprogressClaimsContent.tsx
src/samples/ChildBenefitsClaim/ExistingSubmittedClaimsContent.tsx
src/samples/ChildBenefitsClaim/NewClaimContent.tsx
src/samples/ChildBenefitsClaim/UserPortal.tsx
src/samples/ChildBenefitsClaim/index.test.tsx
src/samples/ChildBenefitsClaim/index.tsx

US-12652 - Apply - Claimant - One submitted claim per day and US-12640 - Apply - claimant - only one in progress claim

---

package.json
src/components/AppComponents/AppFooter/index.tsx
src/components/AppComponents/AppHeader/index.tsx
src/samples/AppSelector/index.tsx
src/samples/AppSelector/mobileApp.tsx
src/samples/HighIncomeCase/reuseables/AppHeader.tsx

As a Customer using the HMRC Mobile App, I want the Header and Footer in the journey to be generated by the Mobile App, so that navigation is consistent and handled by the app.
New package added for determining user agent string
[react-device-detect](https://www.npmjs.com/package/react-device-detect)

Us 13746 - Added code to conditionally render header and footer based on User Agent String

---

assets/i18n/cy.json
assets/i18n/en.json
src/samples/ChildBenefitsClaim/UserPortal.tsx

Added new text with Welsh translation and updated the key in the i18n language files.

US-14320 replacing the text "Online" with "Get help online"

---

src/samples/ProofOfEntitlement/ProofOfEntitlement.tsx

fixed casing for 
https://hmrc-agilestudio.pegacloud.net/prweb/app/HMRCAgileStudio/2MOlO7Qp1L2wiUXGllwsyTNSKvH8ojhkbfAH2oCCy8A*/!STANDARD?pzPostData=-50634458
it comes under the bug ticket: https://hmrc-agilestudio.pegacloud.net/prweb/app/HMRCAgileStudio/2MOlO7Qp1L2wiUXGllwsyTNSKvH8ojhkbfAH2oCCy8A*/!STANDARD?pzPostData=-50634458

fixed caseing
